repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-added-large-files
    - id: pretty-format-json
      args:
      - "--indent=2"
      - "--autofix"
    - id: check-json
    - id: check-yaml
    - id: check-toml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--line-length=120, --target-version=py38]
        additional_dependencies: [
          'click<8.0.0',
        ]

  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 0.11.0
    hooks:
      - id: flakeheaven
        additional_dependencies: [
          'wemake-python-styleguide==0.16.1',
          'pyflakes==2.4.0',
          'pycodestyle==2.8.0',
          'bandit==1.7.4',
          'flake8==4.0.1',
          'flake8-bandit==3.0.0',
          'flake8-broken-line==0.4.0',
          'flake8-bugbear==22.3.23',
          'flake8-commas==2.1.0',
          'flake8-comprehensions==3.8.0',
          'flake8-debugger==4.0.0',
          'flake8-docstrings==1.6.0',
          'flake8-eradicate==1.2.0',
          'flake8-isort==4.1.1',
          'flake8-plugin-utils==1.3.2',
          'flake8-polyfill==1.0.2',
          'flake8-pytest-style==1.6.0',
          'flake8-quotes==3.3.1',
          'flake8-rst-docstrings==0.2.5',
          'flake8-string-format==0.3.0',
          ]
        args: [
          "--config='pyproject.toml'",
          "--max-line-complexity=16"
        ]
