import os

__all__ = (
    "CELERY_TASK_ALWAYS_EAGER",
    "CELERY_TASK_TRACK_STARTED",
    "COMMON_CELERY_QUEUE",
    "CRITICAL_CELERY_QUEUE",
    "API_CELERY_QUEUE",
    "CELERY_BROKER",
    "CELERY_BACKEND",
    "CELERY_TASK_SERIALIZER",
    "CELERY_RESULT_SERIALIZER",
)

CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_TRACK_STARTED = True
COMMON_CELERY_QUEUE = "celery"
CRITICAL_CELERY_QUEUE = os.getenv("CRITICAL_CELERY_QUEUE", COMMON_CELERY_QUEUE)
API_CELERY_QUEUE = os.getenv("API_CELERY_QUEUE", COMMON_CELERY_QUEUE)
CELERY_BROKER = os.getenv("CELERY_BROKER")
CELERY_BACKEND = os.getenv("CELERY_BACKEND")
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
