# Generated by Django 3.2.9 on 2022-04-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notification_text", models.TextField()),
                (
                    "operation_system",
                    models.SmallIntegerField(
                        choices=[(0, "Any os"), (1, "Apple MacOS"), (2, "Linux"), (3, "Microsoft Windows")], default=0
                    ),
                ),
            ],
        ),
    ]
