# Generated by Django 3.2.9 on 2022-06-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="post",),
        migrations.RemoveField(model_name="like", name="post",),
        migrations.AddField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
        ),
        migrations.AddField(model_name="comment", name="object_id", field=models.PositiveIntegerField(),),
        migrations.AddField(
            model_name="like",
            name="content_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
        ),
        migrations.AddField(model_name="like", name="object_id", field=models.PositiveIntegerField(),),
    ]
