# Generated by Django 3.2.9 on 2022-06-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("blog_app", "0002_auto_20220622_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
            ),
        ),
        migrations.AlterField(
            model_name="comment", name="object_id", field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="like",
            name="content_type",
            field=models.ForeignKey(
                default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
            ),
        ),
        migrations.AlterField(
            model_name="like", name="object_id", field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["content_type", "object_id"], name="blog_app_co_content_50f556_idx"),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(fields=["content_type", "object_id"], name="blog_app_li_content_5c8b85_idx"),
        ),
    ]
