# Generated by Django 3.2.9 on 2022-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0003_auto_20220622_1236"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment", index=models.Index(fields=["user"], name="blog_app_co_user_id_a93674_idx"),
        ),
        migrations.AddIndex(
            model_name="comment", index=models.Index(fields=["create_date"], name="blog_app_co_create__132394_idx"),
        ),
        migrations.AddIndex(
            model_name="like", index=models.Index(fields=["user"], name="blog_app_li_user_id_1567a0_idx"),
        ),
        migrations.AddIndex(
            model_name="like", index=models.Index(fields=["create_date"], name="blog_app_li_create__1c1419_idx"),
        ),
        migrations.AddIndex(
            model_name="post", index=models.Index(fields=["user"], name="blog_app_po_user_id_46ddaa_idx"),
        ),
        migrations.AddIndex(
            model_name="post", index=models.Index(fields=["create_date"], name="blog_app_po_create__bd461b_idx"),
        ),
    ]
