# Generated by Django 3.2.9 on 2022-06-22 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("blog_app", "0004_auto_20220622_1243"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="like", unique_together={("user", "content_type", "object_id")},),
    ]
